using System;

class Program
{
    static void Main(string[] args)
    {
        throw new Exception("本当は例外など起きていない。");
    }
}
